// Code generated by entc, DO NOT EDIT.

package city

const (
	// Label holds the string label denoting the city type in the database.
	Label = "city"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeStreet holds the string denoting the street edge name in mutations.
	EdgeStreet = "street"
	// Table holds the table name of the city in the database.
	Table = "cities"
	// StreetTable is the table that holds the street relation/edge. The primary key declared below.
	StreetTable = "street_cities"
	// StreetInverseTable is the table name for the Street entity.
	// It exists in this package in order to avoid circular dependency with the "street" package.
	StreetInverseTable = "streets"
)

// Columns holds all SQL columns for city fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// StreetPrimaryKey and StreetColumn2 are the table columns denoting the
	// primary key for the street relation (M2M).
	StreetPrimaryKey = []string{"street_id", "city_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
