// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/encero/ruian_parser/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
