// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/encero/ruian_parser/ent/addressplace"
	"github.com/encero/ruian_parser/ent/predicate"
)

// AddressPlaceDelete is the builder for deleting a AddressPlace entity.
type AddressPlaceDelete struct {
	config
	hooks    []Hook
	mutation *AddressPlaceMutation
}

// Where appends a list predicates to the AddressPlaceDelete builder.
func (apd *AddressPlaceDelete) Where(ps ...predicate.AddressPlace) *AddressPlaceDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *AddressPlaceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(apd.hooks) == 0 {
		affected, err = apd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AddressPlaceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			apd.mutation = mutation
			affected, err = apd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(apd.hooks) - 1; i >= 0; i-- {
			if apd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = apd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, apd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *AddressPlaceDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *AddressPlaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: addressplace.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: addressplace.FieldID,
			},
		},
	}
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
}

// AddressPlaceDeleteOne is the builder for deleting a single AddressPlace entity.
type AddressPlaceDeleteOne struct {
	apd *AddressPlaceDelete
}

// Exec executes the deletion query.
func (apdo *AddressPlaceDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{addressplace.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *AddressPlaceDeleteOne) ExecX(ctx context.Context) {
	apdo.apd.ExecX(ctx)
}
