// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AddressPlace is the predicate function for addressplace builders.
type AddressPlace func(*sql.Selector)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Street is the predicate function for street builders.
type Street func(*sql.Selector)
